export enum Category {
    SHORT_SLEEVE_TOP = 'Short Sleeve Top',
    LONG_SLEEVE_TOP = 'Long Sleeve Top',
    SHORT_SLEEVE_OUTWEAR = 'Short Sleeve Outwear',
    LONG_SLEEVE_OUTWEAR = 'Long Sleeve Outwear',
    VEST = 'Vest',
    SLING = 'Sling',
    SHORTS = 'Shorts',
    TROUSERS = 'Trousers',
    SKIRT = 'Skirt',
    SHORT_SLEEVE_DRESS = 'Short Sleeve Dress',
    LONG_SLEEVE_DRESS = 'Long Sleeve Dress',
    VEST_DRESS = 'Vest Dress',
    SLING_DRESS = 'Sling Dress',
    ACCESSORIES = 'Accessories',
    OTHER = 'Other',
}